import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'
import { space } from 'postcss/lib/list'
import { cn } from '@/lib/utils'
import Header from '@/components/Header/Header'

const spaceGrotest = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn('bg-background', spaceGrotest.className)}>
        <Header />
        {children}
      </body>
    </html>
  )
}
